kind: pipeline
name: default
steps:
- name: test and build
  image: clojure:openjdk-11-lein
  commands:
  - lein deps
  - lein test
  - lein uberjar
- name: container build and push
  image: plugins/gcr
  settings:
    registry: us.gcr.io
    repo: strokeless/strokeless
    tags: ${DRONE_COMMIT_SHA}
    json_key:
      from_secret: google_credentials
  when:
    branch:
    - main
- name: deploy
  image: google/cloud-sdk
  environment:
    GOOGLE_KEYS:
      from_secret: google_credentials
  commands:
  - printf "%s" "$${GOOGLE_KEYS}" > key.json
  - gcloud auth activate-service-account --key-file=key.json
  - gcloud run deploy strokeless --image us.gcr.io/strokeless/strokeless:${DRONE_COMMIT_SHA}

