kind: pipeline
name: default
steps:
- name: test and build
  image: clojure:openjdk-11-lein
  commands:
  - lein deps
  - lein test
  - lein uberjar
- name: docker
  image: plugins/gcr
  settings:
    registry: us.gcr.io
    repo: strokeless/strokeless
    tags: ${DRONE_COMMIT_SHA}
    json_key:
      from_secret: google_credentials
  when:
    branch:
    - main
