version: 2
jobs:
  build:
    docker:
    - image: circleci/clojure:openjdk-11-lein-2.9.1
    steps:
    - checkout
    - run: lein deps
    - run: lein test
    - run: lein uberjar
    - setup_remote_docker
    - run: docker build -t nsmith5/strokeless:${CIRCLE_SHA1} .
    - deploy:
        command: |
          if [ "${CIRCLE_BRANCH}" == "main" ]; then
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push nsmith5/strokeless:${CIRCLE_SHA1}
          fi
