version: 2.1
orbs:
  cloudrun: circleci/gcp-cloud-run@1.0.2
workflows:  
  build_and_deploy_to_managed_workflow:
    jobs:
    - build
jobs:
  build:
    docker:
    - image: circleci/clojure:openjdk-11-lein-2.9.1
    steps:
    - checkout
    - run: lein deps
    - run: lein test
    - run: lein uberjar
    - cloudrun/init
    - cloudrun/build:
        tag: 'us.gcr.io/${GOOGLE_PROJECT_ID}/test-${CIRCLE_SHA1}'
    - cloudrun/deploy:
        platform: managed
        region: us-west1
        image: 'us.gcr.io/${GOOGLE_PROJECT_ID}/test-${CIRCLE_SHA1}'
        service-name: strokeless
        unauthenticated: true
    - setup_remote_docker
    - run: docker build -t nsmith5/strokeless:${CIRCLE_SHA1} .
    - deploy:
        command: |
          if [ "${CIRCLE_BRANCH}" == "main" ]; then
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push nsmith5/strokeless:${CIRCLE_SHA1}
          fi
